server:
  port: 8001
  address: 0.0.0.0
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisDB?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 20
      leak-detection-threshold: 5000
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  # 确保 SqlSession 由 Spring 管理
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-executor-type: reuse # 重用预处理语句
    cache-enabled: true
    local-cache-scope: session
oss.endpoint: oss-cn-beijing.aliyuncs.com
oss.accessKeyId: LTAI5t8tbEDxXwWupFqPaBEj
oss.accessKeySecret: ETendtTuR2F84iZPvEeJDbChDr428C
oss.bucketName: dashijian
oss.expireSeconds: 360000